/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as PolicyCheckRouteImport } from './routes/policy-check'
import { Route as LifeScoreRouteImport } from './routes/life-score'
import { Route as HiddenMoneyRouteImport } from './routes/hidden-money'
import { Route as IndexRouteImport } from './routes/index'

const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyCheckRoute = PolicyCheckRouteImport.update({
  id: '/policy-check',
  path: '/policy-check',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeScoreRoute = LifeScoreRouteImport.update({
  id: '/life-score',
  path: '/life-score',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenMoneyRoute = HiddenMoneyRouteImport.update({
  id: '/hidden-money',
  path: '/hidden-money',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hidden-money': typeof HiddenMoneyRoute
  '/life-score': typeof LifeScoreRoute
  '/policy-check': typeof PolicyCheckRoute
  '/screener': typeof ScreenerRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hidden-money': typeof HiddenMoneyRoute
  '/life-score': typeof LifeScoreRoute
  '/policy-check': typeof PolicyCheckRoute
  '/screener': typeof ScreenerRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hidden-money': typeof HiddenMoneyRoute
  '/life-score': typeof LifeScoreRoute
  '/policy-check': typeof PolicyCheckRoute
  '/screener': typeof ScreenerRoute
  '/talk': typeof TalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hidden-money'
    | '/life-score'
    | '/policy-check'
    | '/screener'
    | '/talk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hidden-money'
    | '/life-score'
    | '/policy-check'
    | '/screener'
    | '/talk'
  id:
    | '__root__'
    | '/'
    | '/hidden-money'
    | '/life-score'
    | '/policy-check'
    | '/screener'
    | '/talk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HiddenMoneyRoute: typeof HiddenMoneyRoute
  LifeScoreRoute: typeof LifeScoreRoute
  PolicyCheckRoute: typeof PolicyCheckRoute
  ScreenerRoute: typeof ScreenerRoute
  TalkRoute: typeof TalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-check': {
      id: '/policy-check'
      path: '/policy-check'
      fullPath: '/policy-check'
      preLoaderRoute: typeof PolicyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-score': {
      id: '/life-score'
      path: '/life-score'
      fullPath: '/life-score'
      preLoaderRoute: typeof LifeScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-money': {
      id: '/hidden-money'
      path: '/hidden-money'
      fullPath: '/hidden-money'
      preLoaderRoute: typeof HiddenMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HiddenMoneyRoute: HiddenMoneyRoute,
  LifeScoreRoute: LifeScoreRoute,
  PolicyCheckRoute: PolicyCheckRoute,
  ScreenerRoute: ScreenerRoute,
  TalkRoute: TalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
